from __future__ import annotations

from lockknife.core._case_models import (
    CaseArtifact,
    CaseArtifactRegistration,
    CaseJobStep,
    CaseJob,
    CaseRuntimeScript,
    CaseRuntimeSession,
    CaseManifest,
)

from lockknife.core._case_common import (
    _utc_now,
    _sha256_file,
    _manifest_path,
    _job_log_path,
    _runtime_session_log_path,
    _runtime_session_summary_path,
    case_output_path,
    _normalize_case_path,
    create_case_workspace,
    load_case_manifest,
    save_case_manifest,
    _json_safe_value,
)

from lockknife.core._case_artifacts import (
    _artifact_ids_for_paths,
    find_case_artifact,
    find_case_artifact_by_id,
    _sorted_filter_values,
    _artifact_filter_payload,
    _select_case_artifacts,
    _latest_artifact_index_for_path,
    _artifact_registration_identity_matches,
    _artifact_registration_payload_matches,
    _artifact_matches_text,
    _artifact_summary_payload,
    query_case_artifacts,
    case_artifact_details,
    case_artifact_lineage,
    register_case_artifact,
    register_case_artifact_with_status,
)

from lockknife.core._case_jobs import (
    _next_job_id,
    _find_job_index,
    _job_step,
    _replace_job_step_status,
    _job_log_event,
    _job_summary_payload,
    _job_logs_tail,
    _job_detail_payload,
    _workflow_kind_for_action,
    _job_terminal,
    _job_resumable_status,
    _job_artifact_ids_from_payload,
    start_case_job,
    complete_case_job,
    fail_case_job,
    query_case_jobs,
    case_job_details,
    case_job_rerun_context,
)

from lockknife.core._case_runtime import (
    _next_runtime_session_id,
    _find_runtime_session_index,
    _next_runtime_script_id,
    _runtime_script_payload,
    _runtime_session_summary_payload,
    _runtime_session_logs_tail,
    _runtime_session_detail_payload,
    _write_runtime_session_summary,
    start_case_runtime_session,
    add_case_runtime_session_script,
    update_case_runtime_session,
    record_case_runtime_session_event,
    query_case_runtime_sessions,
    case_runtime_session_details,
)

from lockknife.core._case_reporting import (
    summarize_case_manifest,
    _resolve_case_artifact_path,
    case_evidence_inventory,
    case_integrity_report,
    case_chain_of_custody_items,
    case_chain_of_custody_report,
    generate_case_chain_of_custody,
    case_lineage_graph,
    _add_path_to_zip,
    export_case_bundle,
)

__all__ = [
    "CaseArtifact",
    "CaseArtifactRegistration",
    "CaseJobStep",
    "CaseJob",
    "CaseRuntimeScript",
    "CaseRuntimeSession",
    "CaseManifest",
    "case_output_path",
    "create_case_workspace",
    "load_case_manifest",
    "save_case_manifest",
    "find_case_artifact",
    "find_case_artifact_by_id",
    "query_case_artifacts",
    "case_artifact_details",
    "case_artifact_lineage",
    "register_case_artifact",
    "register_case_artifact_with_status",
    "start_case_job",
    "complete_case_job",
    "fail_case_job",
    "query_case_jobs",
    "case_job_details",
    "case_job_rerun_context",
    "start_case_runtime_session",
    "add_case_runtime_session_script",
    "update_case_runtime_session",
    "record_case_runtime_session_event",
    "query_case_runtime_sessions",
    "case_runtime_session_details",
    "summarize_case_manifest",
    "case_evidence_inventory",
    "case_integrity_report",
    "case_chain_of_custody_items",
    "case_chain_of_custody_report",
    "generate_case_chain_of_custody",
    "case_lineage_graph",
    "export_case_bundle",
]
