from collections.abc import Callable, Sequence

def parse_dex_header_json(data: bytes) -> str: ...
def parse_elf_header_json(data: bytes) -> str: ...
def detect_iocs_native(data: bytes) -> str: ...
def sha1_hex(data: bytes) -> str: ...
def sha256_hex(data: bytes) -> str: ...
def sha512_hex(data: bytes) -> str: ...
def md5_hex(data: bytes) -> str: ...
def hmac_sha256(key: bytes, data: bytes) -> str: ...
def aes256gcm_encrypt(
    key: bytes, nonce: bytes, plaintext: bytes, associated_data: bytes
) -> bytes: ...
def aes256gcm_decrypt(
    key: bytes, nonce: bytes, ciphertext: bytes, associated_data: bytes
) -> bytes: ...
def bruteforce_numeric_pin(target_hash_hex: str, algo: str, length: int) -> str | None: ...
def dictionary_attack(target_hash_hex: str, algo: str, wordlist_path: str) -> str | None: ...
def dictionary_attack_rules(
    target_hash_hex: str, algo: str, wordlist_path: str, max_suffix: int
) -> str | None: ...
def bruteforce_android_pin_sha1(target_sha1_hex: str, salt: int, length: int) -> str | None: ...
def recover_android_gesture(gesture_key_bytes: bytes) -> str: ...
def scan_patterns_json(data: bytes, patterns: Sequence[str]) -> str: ...
def sqlite_table_to_json(path: str, table: str, limit: int) -> str: ...
def correlate_artifacts_json(json_blobs: Sequence[str]) -> str: ...
def parse_ipv4_header_json(data: bytes) -> str: ...
def yara_scan_bytes(rules_src: str, data: bytes) -> str: ...
def yara_scan_file_rules(rules_path: str, data: bytes) -> str: ...
def yara_cache_stats() -> str: ...
def craft_wifi_beacon(ssid: str, bssid: str, channel: int) -> bytes: ...
def craft_wifi_probe_request(ssid: str, bssid: str) -> bytes: ...
def craft_wifi_deauth(bssid: str, client_mac: str) -> bytes: ...
def craft_wifi_auth(bssid: str, client_mac: str) -> bytes: ...
def craft_wifi_association(bssid: str, client_mac: str, ssid: str) -> bytes: ...
def craft_bluetooth_lmp(bd_addr: str, features: int) -> bytes: ...
def parse_wifi_frame(packet_bytes: bytes) -> str: ...
def validate_wifi_checksum(packet_bytes: bytes) -> bool: ...
def bruteforce_wps_pin_checksum(pin: int) -> bool: ...
def bruteforce_wps_pin_parallel(bssid: str, max_pin: int, threads: int) -> str | None: ...
def wps_pixie_dust_accelerated(eapol_packets: list[bytes]) -> str: ...
def generate_wps_pins(start: int, end: int) -> list[str]: ...
def bruteforce_wps_pin_with_checksum(
    target_hash_hex: str, algo: str, start_pin: int, end_pin: int, threads: int
) -> str | None: ...
def pbkdf2_sha1(passphrase: bytes, ssid: bytes, iterations: int) -> str: ...
def pbkdf2_sha1_parallel(passphrase: bytes, ssid: bytes, iterations: int, threads: int) -> str: ...
def hmac_sha1_vector(key: bytes, data_chunks: list[bytes]) -> str: ...
def derive_psk(passphrase: bytes, ssid: bytes) -> str: ...
def validate_handshake(anonce: bytes, snonce: bytes, mic: bytes, psk_hex: str) -> bool: ...
def crack_handshake(
    anonce: bytes, snonce: bytes, mic: bytes, ssid: bytes, wordlist_path: str
) -> str | None: ...
def crack_handshake_parallel(
    anonce: bytes,
    snonce: bytes,
    mic: bytes,
    ssid: bytes,
    wordlist_path: str,
    threads: int,
) -> str | None: ...
def scan_ports_parallel(target_ip: str, ports: list[int], threads: int) -> list[int]: ...
def scan_port_range(target_ip: str, start_port: int, end_port: int, threads: int) -> list[int]: ...
def scan_common_ports(target_ip: str, threads: int) -> list[int]: ...
def scan_service_banner(target_ip: str, port: int, timeout_ms: int) -> str: ...
def ping_sweep_parallel(ip_range: list[str], threads: int) -> list[str]: ...
def tcp_syn_scan(target_ip: str, port: int) -> bool: ...
def udp_scan(target_ip: str, port: int) -> bool: ...
def scan_top_ports(target_ip: str, threads: int, count: int) -> list[int]: ...
def analyze_pcap_native(file_path: str) -> str: ...
def run_tui(
    callback: Callable[[str, dict[str, object]], dict[str, object]],
    catalog_json: str | None = None,
) -> None: ...
