from collections.abc import Callable, Sequence

def parse_dex_header_json(data: bytes) -> str: ...
def parse_elf_header_json(data: bytes) -> str: ...
def sha1_hex(data: bytes) -> str: ...
def sha256_hex(data: bytes) -> str: ...
def sha512_hex(data: bytes) -> str: ...
def md5_hex(data: bytes) -> str: ...
def hmac_sha256(key: bytes, data: bytes) -> str: ...
def aes256gcm_encrypt(
    key: bytes, nonce: bytes, plaintext: bytes, associated_data: bytes
) -> bytes: ...
def aes256gcm_decrypt(
    key: bytes, nonce: bytes, ciphertext: bytes, associated_data: bytes
) -> bytes: ...
def bruteforce_numeric_pin(target_hash_hex: str, algo: str, length: int) -> str | None: ...
def dictionary_attack(target_hash_hex: str, algo: str, wordlist_path: str) -> str | None: ...
def dictionary_attack_rules(
    target_hash_hex: str, algo: str, wordlist_path: str, max_suffix: int
) -> str | None: ...
def bruteforce_android_pin_sha1(target_sha1_hex: str, salt: int, length: int) -> str | None: ...
def recover_android_gesture(gesture_key_bytes: bytes) -> str: ...
def scan_patterns_json(data: bytes, patterns: Sequence[str]) -> str: ...
def sqlite_table_to_json(path: str, table: str, limit: int) -> str: ...
def correlate_artifacts_json(json_blobs: Sequence[str]) -> str: ...
def parse_ipv4_header_json(data: bytes) -> str: ...
def yara_scan_bytes(rules_src: str, data: bytes) -> str: ...
def yara_scan_file_rules(rules_path: str, data: bytes) -> str: ...
def yara_cache_stats() -> str: ...
def run_tui(callback: Callable[[str, dict[str, object]], dict[str, object]]) -> None: ...
